routes/web.php
<?php

use App\Http\Controllers\AdminMovieController;
use App\Http\Controllers\AdminPlanController;
use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", function () {
    return view("homepage");
})->name('homepage');

Route::middleware(['auth', 'verified'])->prefix('profile')->name('profile.')->group(function () {
    Route::get('/', [UserController::class, 'profile'])->name('index');
    Route::post('/update-password', [UserController::class, 'updatePassword'])->name('update-password');
    Route::middleware(['password.confirm'])->delete('/delete-profile', [UserController::class, 'deleteProfile'])->name('delete');
    Route::get('/manage-subscriptions', [UserController::class, 'manageSubscriptions'])->name('manage-subscriptions');
});

Route::get('/subscribe/{plan}/{priceData}', [UserController::class, 'subscribe'])->name('plan.subscribe');
Route::get('movie/thumbnail/component', [MovieController::class, 'getThumbnailComponent'])->name('movie.thumbnailComponent');


Route::middleware(['auth'])->name('movie.')->prefix('movie')->group(function () {
    Route::get('/thumbnail/{id}', [MovieController::class, 'getThumbnail'])->name('thumbnail');
    Route::post('/fav/{id}', [MovieController::class, 'addToFavourites'])->name('fav');
    Route::post('/unfav/{id}', [MovieController::class, 'removeFromFavourites'])->name('unfav');
    Route::post('/ban/{id}', [MovieController::class, 'removeFromRecommendations'])->name('ban');
    Route::post('/unban/{id}', [MovieController::class, 'addToRecommendations'])->name('unban');
});
Route::middleware(['auth'])->resource('movie', MovieController::class, ['except' => ['show']]);
Route::middleware(['auth', 'verified', 'subscribed'])->get('/movie/{movie}', [MovieController::class, 'show'])->name('movie.show');


Route::resource('genres', GenreController::class);

Route::get("/logout", function () {
    \Illuminate\Support\Facades\Auth::logout();
    return redirect("/");
});


Route::prefix('admin')->name('admin.')->middleware(['auth', 'verified', 'admin'])->group(function () {
    Route::get('/', function () {
        return view("admin.index");
    })->name('index');
    // Route::get('/users', function () {
    //     return view("admin.users");
    // })->name('users');
    Route::resource('users', AdminUserController::class);
    Route::resource('movies', AdminMovieController::class);
    Route::resource('plans', AdminPlanController::class);
    Route::post('/users/{id}/toggle-admin', [UserController::class, 'toggleAdmin'])->name('users.toggle-admin');
    Route::post('/plans/reorder', [AdminPlanController::class, 'reorder'])->name('plans.reorder');
    Route::post('/plans/{id}/restore', [AdminPlanController::class, 'restore'])->name('plans.restore');
    Route::post('/plans/{id}/toggle-visibility', [AdminPlanController::class, 'toggleVisibility'])->name('plans.toggle-visibility');

    // Route::resource('users', UserController::class);
});

resources/views/admin/index.blade.php
<x-layouts.admin>
    {{-- <x-slot name="title"> --}}
        {{-- Dashboard --}}
        {{-- </x-slot> --}}

    <div class="uk-container uk-margin-top">
        <h1> Admin panel </h1>

        <nav class="uk-grid uk-child-width-1-1 uk-child-width-1-2@m uk-child-width-1-3@l" uk-grid>
            <div>
                <div class="uk-card uk-card-primary uk-card-body">
                    <h3 class="uk-card-title">Users</h3>
                    <ul>
                        <li>
                            <a href="{{route('admin.users.index')}}">Manage users</a>
                        </li>
                        {{-- <li> --}}
                            {{-- <a href="{{route('register')}}">Registration link</a> --}}
                            {{-- </li> --}}
                    </ul>
                </div>
            </div>

            <div>
                <div class="uk-card uk-card-primary uk-card-body">
                    <h3 class="uk-card-title">Movies</h3>
                    <ul>
                        <li>
                            <a href="{{route('admin.movies.index')}}">Manage movies</a>
                        </li>
                        <li>
                            <a href="{{route('admin.movies.create')}}">Create new movie</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div>
                <div class="uk-card uk-card-primary uk-card-body">
                    <h3 class="uk-card-title">Plans</h3>
                    <ul>
                        <li>
                            <a href="{{route('admin.plans.index')}}">Manage plans</a>
                        </li>
                        <li>
                            <a href="#add-plan-modal" uk-toggle>Create new plan</a>
                        </li>
                        <li>
                            <a href="https://dashboard.stripe.com/test/dashboard" target="_blank">Manage prices</a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
    </div>

    <x-admin.add-plan-modal />

</x-layouts.admin>

resources/views/admin/movies.blade.php
<x-layouts.admin>

    <div class="uk-container uk-margin-top uk-margin-bottom">
        <h1> Manage movies </h1>

        @php
        $request = request();

        $page = $request->has('page') ? $request->get('page') : 1;
        $perPage = $request->has('perPage') ? $request->get('perPage') : 20;

        $genreFilter = request('genre', null);
        $search = $request->filled('search') ? $request->get('search') : null;


        $query = App\Models\Movie::query();
        // if(is_null($genreFilter)){
        // }
        // else{
        // $query = App\Models\Genre::where('name', $genreFilter)->firstOrFail()->movies();
        // }

        if($genreFilter !== null)
        $query = $query->whereBelongsTo(App\Models\Genre::where('name', $genreFilter)->firstOrFail());



        if($search !== null)
        $query = $query->where(fn($query)=>
        $query
        ->orWhere('title', 'like', '%' . $search . '%')
        ->orWhere('description', 'like', '%' . $search . '%')
        ->orWhere(fn($q)=>
        App\Models\Genre::where('name','like' ,'%'.$search.'%')->get()->whenNotEmpty(
        fn($genres)=>
        $q->orWhereBelongsTo($genres)
        ,
        fn($empty)=>$q
        )
        )
        ->orWhere('year', '=', $search)
        );

        $data = $query->get();


        $movies = new \Illuminate\Pagination\LengthAwarePaginator($data->slice(($page-1)*$perPage, $perPage),
        $data->count(), $perPage, $page, [
        'path' => $request->url(),
        'query' => $request->query(),
        ]);
        @endphp

        <p class="uk-text-muted">
            Tip: hover over movie link to see description
        </p>

        <a href="{{route('admin.movies.create')}}" class="uk-button uk-button-primary">
            Create new movie
        </a>

        <div class=" uk-margin">
            <form action="" method="GET" id="filters" class="uk-flex">
                <div class="uk-margin-right">
                    <div uk-form-custom="target: > * > span:first-child">
                        <select name="genre" onchange="document.querySelector('#filters').submit()">
                            <option value="">All genres</option>
                            @foreach (App\Models\Genre::all() as $g)
                            <option value="{{strtolower($g->name)}}" @selected(isset($genreFilter) &&
                                $genreFilter==strtolower($g->name))>
                                {{$g->name}}
                            </option>
                            @endforeach
                        </select>

                        <button class="uk-button uk-button-default" type="button" tabindex="-1">
                            <span></span>
                            <span uk-icon="icon: chevron-down"></span>
                        </button>
                    </div>
                </div>
                <div class="uk-margin-right">
                    <div uk-form-custom="target: > * > span:first-child">
                        <select name="perPage" onchange="document.querySelector('#filters').submit()">
                            @php
                            $options = collect([5,10,20,30,40,50,100]);
                            @endphp
                            @foreach ($options->merge([$perPage])->unique()->sort() as $p)
                            <option value="{{$p}}" @selected($perPage==$p)>
                                {{$p}}
                            </option>
                            @endforeach
                        </select>

                        <button class="uk-button uk-button-default" type="button" tabindex="-1">
                            Per page: <span></span>
                            <span uk-icon="icon: chevron-down"></span>
                        </button>
                    </div>
                </div>

                <div>
                    <div class="uk-search uk-search-default uk-margin-right">
                        <span uk-search-icon class="uk-search-icon-flip"></span>
                        <input title="Search by name, description, genre or year" uk-tooltip class="uk-search-input" value="{{request('search','')}}" onfocus="this.select()"
                            name="search" type="search" placeholder="Search">
                    </div>
                </div>


                <a href="{{route('admin.movies.index')}}" class="uk-button uk-button-default">
                    Clear filters
                </a>
            </form>
        </div>

        {{$movies->links()}}

        <table class="uk-table uk-table-middle uk-table-small uk-table-hover uk-table-striped">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Genre</th>
                <th>Year</th>
                <th>Date added</th>
                <th>Times watched</th>
                <th>Actions</th>
            </tr>
            @foreach ($movies->items() as $m)
            <tr id="row-{{$movies->firstItem() + $loop->index}}">
                <td>{{$movies->firstItem() + $loop->index}}</td>
                <td>
                    <a href="{{route('movie.show', ['movie'=>$m->hashid()])}}">
                        {{$m->title}}
                    </a>
                    <div uk-drop="pos: right-center;delay-show: 200; delay-hide:0">
                        <div class="uk-card uk-card-body uk-card-default">
                            {{$m->description}}
                        </div>
                    </div>
                </td>
                <td>{{$m->genre->name}}</td>
                <td>{{$m->year}}</td>
                <td>{{$m->created_at}}</td>
                <td>{{array_reduce(array_map(fn($v)=>$v['times_watched'],$m->watchedBy()->get()->toArray()),
                    fn($a,$b)=>$a+$b, 0)}}</td>
                <td>
                    <div class="uk-flex uk-flex-start">
                        <a title="Edit movie" uk-tooltip href="{{route('admin.movies.edit', ['movie'=>$m->hashid()])}}"
                            class="uk-margin-small-left uk-button uk-button-default uk-button-small">
                            <span uk-icon="icon: pencil"></span>
                        </a>
                        <form action="{{route('admin.movies.destroy', ['movie'=>$m->hashid()])}}" method="POST">
                            @csrf
                            @method('delete')
                            <button title="Delete movie" uk-tooltip class="uk-margin-small-left uk-button uk-button-default uk-button-small
                                uk-button-danger">
                                <span uk-icon="icon: trash"></span>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
            @endforeach

        </table>
        {{$movies->links()}}


    </div>

</x-layouts.admin>

resources/views/admin/plans.blade.php
<x-layouts.admin>
    @push('scripts')
    <script>
        document.addEventListener("DOMContentLoaded", ()=>{
            UIkit.util.on('#plans', 'moved', (ev)=>{
                console.log(ev);
                setTimeout(() => {
                    const cards = document.querySelectorAll('.plan-card');
                    axios.post('{{route("admin.plans.reorder")}}',
                        {
                            ids: Array.from(cards).map(v=>v.getAttribute('data-id')),
                        },
                        {
                            withCredentials: true,
                        }
                    )
                    .then(console.log);
                }, 1);
            });
        });
    </script>
    @endpush

    @php
    $plans = App\Models\Plan::withTrashed()->orderBy("order")->get();
    @endphp

    <div class="uk-container uk-margin-top uk-margin-bottom">
        <span>Drag plans to reorder</span>

        <ul id="plans" class="uk-margin-top uk-grid-small uk-child-width-1-2 uk-child-width-1-4@s" uk-sortable=""
            uk-grid>

            @forelse ($plans as $plan)
            <li>
                <div @class(['uk-card', 'uk-card' , 'uk-card-body' , 'uk-text-center' , 'plan-card' , 'uk-card-default'
                    , 'uk-box-shadow-large' ]) data-id="{{$plan->hashid()}}">
                    @php
                    $prod = $plan->getStripeProduct();
                    @endphp
                    <h3>
                        {{$plan->name ?? $prod->name}}
                    </h3>
                    <p>
                        {{$plan->description ?? $prod->description}}
                    </p>
                    @if(!$plan->active)
                    <div class="uk-card-badge uk-label uk-label-default">HIDDEN</div>
                    @endif
                    <div class="uk-flex uk-margin-top">
                        <form method="POST"
                            action="{{route('admin.plans.toggle-visibility', ['id'=>$plan->hashid()])}}">
                            @csrf
                            <button class="uk-button uk-button-default uk-button-small uk-margin-left">{{$plan->active ?
                                'Hide' : 'Show'}}</button>
                        </form>
                        @if($plan->trashed())
                        <div class="uk-card-badge uk-label uk-label-danger">DELETED</div>
                        <form method="POST" action="{{route('admin.plans.restore', ['id'=>$plan->hashid()])}}">
                            @csrf
                            <button class="uk-button uk-button-default uk-button-small uk-margin-left">Restore</button>
                        </form>
                        @else
                        <form method="POST" action="{{route('admin.plans.destroy', ['plan'=>$plan->hashid()])}}">
                            @csrf
                            @method('delete')
                            <button class="uk-button uk-button-danger uk-button-small uk-margin-left">Delete</button>
                        </form>
                        @endif
                    </div>
                </div>
            </li>
            @empty
            <h3>
                Brak planów
            </h3>
            @endforelse
        </ul>
        <div class="uk-margin-large-top">
            <button class="uk-button uk-button-primary uk-margin uk-display-inline-block"
                uk-toggle="#add-plan-modal">Add plan</button>
            <a href="https://dashboard.stripe.com/test/dashboard" target="_blank"
                class="uk-button uk-button-primary uk-margin uk-display-inline-block uk-margin-remove-top">Manage prices</a>

        </div>
    </div>


    <x-admin.add-plan-modal/>
</x-layouts.admin>

resources/views/admin/users.blade.php
<x-layouts.admin>

    <div class="uk-container uk-margin-top uk-margin-bottom">
        <h1> Manage users </h1>

        @php
        $plans = App\Models\Plan::all();
        $request = request();

        $page = $request->filled('page') ? $request->get('page') : 1;
        $perPage = $request->filled('perPage') ? $request->get('perPage') : 20;
        $search = $request->filled('search') ? $request->get('search') : null;

        $isAdminFilter = $request->filled('isAdmin') ? $request->boolean('isAdmin') : null;

        $query = App\Models\User::query();

        if($isAdminFilter !== null)
        $query = App\Models\User::where('is_admin', $isAdminFilter);

        if($search !== null)
        $query = $query->where(fn($query)=>
        $query
        ->orWhere('name', 'like', '%' . $search . '%')
        ->orWhere('email', 'like', '%' . $search . '%')
        );

        $data = $query->get();

        $users = new \Illuminate\Pagination\LengthAwarePaginator($data->slice(($page-1)*$perPage, $perPage),
        $data->count(), $perPage, $page, [
        'path' => $request->url(),
        'query' => $request->query(),
        ]);
        @endphp


        <div class=" uk-margin">
            <form action="" method="GET" id="filters" class="uk-flex">

                <div class="uk-margin-right">
                    <div uk-form-custom="target: > * > span:first-child">
                        <select name="isAdmin" onchange="document.querySelector('#filters').submit()">
                            <option value="" @selected($isAdminFilter===null)>Any</option>
                            <option value="1" @selected($isAdminFilter===true)>Yes</option>
                            <option value="0" @selected($isAdminFilter===false)>No</option>
                        </select>

                        <button class="uk-button uk-button-default" type="button" tabindex="-1">
                            Is admin: <span></span>
                            <span uk-icon="icon: chevron-down"></span>
                        </button>
                    </div>
                </div>
                <div class="uk-margin-right">
                    <div uk-form-custom="target: > * > span:first-child">
                        <select name="perPage" onchange="document.querySelector('#filters').submit()">
                            @php
                            $options = collect([5,10,20,30,40,50,100]);
                            @endphp
                            @foreach ($options->merge([$perPage])->unique()->sort() as $p)
                            <option value="{{$p}}" @selected($perPage==$p)>
                                {{$p}}
                            </option>
                            @endforeach
                        </select>

                        <button class="uk-button uk-button-default" type="button" tabindex="-1">
                            Per page: <span></span>
                            <span uk-icon="icon: chevron-down"></span>
                        </button>
                    </div>
                </div>


                <div>
                    <div class="uk-search uk-search-default uk-margin-right">
                        <span uk-search-icon class="uk-search-icon-flip"></span>
                        <input title="Search by name or email" uk-tooltip class="uk-search-input" value="{{request('search','')}}" onfocus="this.select()"
                            name="search" type="search" placeholder="Search">
                    </div>
                </div>

                <a href="{{route('admin.users.index')}}" class="uk-button uk-button-default">
                    Clear filters
                </a>
            </form>
        </div>

        {{$users->links()}}

        <table class="uk-table uk-table-middle uk-table-small uk-table-hover uk-table-striped">
            <tr>
                <th>#</th>
                <th>Email</th>
                <th>User Full name</th>
                <th>Plan</th>
                <th>Date joined</th>
                <th>Is admin</th>
                <th>Actions</th>
            </tr>
            @foreach ($users->items() as $u)
            <tr>
                <td>{{$users->firstItem() + $loop->index}}</td>
                <td>{{$u->email}}</td>
                <td class="uk-text-truncate uk-preserve-width" uk-tooltip="title:{{$u->name}}; pos:right">{{$u->name}}
                </td>
                @php
                $plan = $u->getPlan();
                @endphp
                <td>{{$plan ?? "-"}}</td>
                {{-- <td>{{$u->watchStatuses()->count()}}</td> --}}
                <td>{{$u->created_at}}</td>
                <td>
                    {{-- {{$u->isAdmin() == 1 ? "Yes" : "No"}} --}}
                    <form method="POST" action="{{route('admin.users.toggle-admin', ['id'=>$u->hashid()])}}">
                        @csrf
                        <button href="" @disabled($u->id == Auth::user()->id) title="{{$u->id == Auth::user()->id ?
                            'You cannot demote yourself':($u->isAdmin() ? "Demote" : "Promote") }}" uk-tooltip
                            @class(['uk-button', 'uk-button-small' , 'uk-button-danger'=> !$u->isAdmin()])>
                            {{$u->isAdmin() ? "Yes" : "No"}}
                        </button>
                    </form>
                </td>
                <td>
                    <div class="uk-flex uk-flex-start">
                        {{-- <button
                            class="uk-margin-small-left uk-button uk-button-muted uk-button-small">Edit</button> --}}
                        <form action="{{route('admin.users.destroy', ['user'=>$u->hashid()])}}" method="POST">
                            @csrf
                            @method('delete')
                            <button title="{{$u->id == Auth::user()->id ? 'You cannot delete yourself':'Delete user'}}"
                                uk-tooltip @disabled($u->id == Auth::user()->id)
                                class="uk-margin-small-left uk-button uk-button-default uk-button-small
                                uk-button-danger">
                                <span uk-icon="icon: trash"></span>
                            </button>
                        </form>

                        {{-- @if ($u->subscribed())
                        <button
                            class="uk-margin-small-left uk-button uk-button-default uk-button-small uk-button-danger">Remove
                            plan</button>
                        @endif --}}
                    </div>

                </td>
            </tr>
            @endforeach

        </table>
        {{$users->links()}}


    </div>



    {{-- <div id="create-user-modal" uk-modal>
        <div class="uk-modal-dialog">
            <button class="uk-modal-close-default" type="button" uk-close></button>
            <div class="uk-modal-header">
                <h2 class="uk-modal-title">Modal Title</h2>
            </div>
            <div class="uk-modal-body">
                <form action="{{route('admin.users.store')}}" method="POST">
                    @csrf
                    <input type="text" name="name" id="name-input">
                    <input type="text" name="email" id="email-input">
                </form>
            </div>
            <div class="uk-modal-footer uk-text-right">
                <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
                <button class="uk-button uk-button-primary" type="button">Save</button>
            </div>
        </div>
    </div> --}}
</x-layouts.admin>