routes/web.php
<?php

use App\Http\Controllers\AdminMovieController;
use App\Http\Controllers\AdminPlanController;
use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", function () {
    return view("homepage");
})->name('homepage');

Route::middleware(['auth', 'verified'])->prefix('profile')->name('profile.')->group(function () {
    Route::get('/', [UserController::class, 'profile'])->name('index');
    Route::post('/update-password', [UserController::class, 'updatePassword'])->name('update-password');
    Route::middleware(['password.confirm'])->delete('/delete-profile', [UserController::class, 'deleteProfile'])->name('delete');
    Route::get('/manage-subscriptions', [UserController::class, 'manageSubscriptions'])->name('manage-subscriptions');
});

Route::get('/subscribe/{plan}/{priceData}', [UserController::class, 'subscribe'])->name('plan.subscribe');
Route::get('movie/thumbnail/component', [MovieController::class, 'getThumbnailComponent'])->name('movie.thumbnailComponent');


Route::middleware(['auth'])->name('movie.')->prefix('movie')->group(function () {
    Route::get('/thumbnail/{id}', [MovieController::class, 'getThumbnail'])->name('thumbnail');
    Route::post('/fav/{id}', [MovieController::class, 'addToFavourites'])->name('fav');
    Route::post('/unfav/{id}', [MovieController::class, 'removeFromFavourites'])->name('unfav');
    Route::post('/ban/{id}', [MovieController::class, 'removeFromRecommendations'])->name('ban');
    Route::post('/unban/{id}', [MovieController::class, 'addToRecommendations'])->name('unban');
});
Route::middleware(['auth'])->resource('movie', MovieController::class, ['except' => ['show']]);
Route::middleware(['auth', 'verified', 'subscribed'])->get('/movie/{movie}', [MovieController::class, 'show'])->name('movie.show');


Route::resource('genres', GenreController::class);

Route::get("/logout", function () {
    \Illuminate\Support\Facades\Auth::logout();
    return redirect("/");
});


Route::prefix('admin')->name('admin.')->middleware(['auth', 'verified', 'admin'])->group(function () {
    Route::get('/', function () {
        return view("admin.index");
    })->name('index');
    // Route::get('/users', function () {
    //     return view("admin.users");
    // })->name('users');
    Route::resource('users', AdminUserController::class);
    Route::resource('movies', AdminMovieController::class);
    Route::resource('plans', AdminPlanController::class);
    Route::post('/users/{id}/toggle-admin', [UserController::class, 'toggleAdmin'])->name('users.toggle-admin');
    Route::post('/plans/reorder', [AdminPlanController::class, 'reorder'])->name('plans.reorder');
    Route::post('/plans/{id}/restore', [AdminPlanController::class, 'restore'])->name('plans.restore');
    Route::post('/plans/{id}/toggle-visibility', [AdminPlanController::class, 'toggleVisibility'])->name('plans.toggle-visibility');

    // Route::resource('users', UserController::class);
});

app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Auth\Access\Response;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Vinkla\Hashids\Facades\Hashids;

class Genre extends Model
{
    static  $HASHIDS_NUMBER = 1;

    use HasFactory, \App\Traits\Hashids;

    public $timestamps = false;

    protected $fillable = ["name"];

    public function movies()
    {
        return $this->hasMany(Movie::class);
    }

}

app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\MovieCollection;
use App\Http\Resources\MovieResource;
use App\Models\Genre;
use App\Models\Movie;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Gate;

class GenreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view("genre.index");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param string $genre_id
     * @return Response
     */
    public function show(string $genre_id)
    {
        $genre = Genre::query()->where("name", $genre_id)->get();
        if ($genre->isNotEmpty()) return view("genre.single", ["genre" => $genre[0]]);

        $genre = Genre::fromHashId($genre_id);
        return view("genre.single", ["genre" => $genre]);
    }

    /**
     * Display the specified resource.
     *
     * @param string $genre_id
     * @param Request $request
     * @return Response
     */
    public function showMovies(Request $request, string $genre_id)
    {
        abort_if(!$request->acceptsJson(), 400);

        $genre = Genre::query()->where("name", $genre_id)->get();
        if ($genre->isEmpty()) {
            $genre = Genre::fromHashId($genre_id);
        }

        $movies = Movie::query()->whereBelongsTo($genre)->simplePaginate(16, page: $request->page);
//        $items = $movies->items();
//        $items = array_map(function ($item) {
//            return $item->toPageValue();
//        }, $items);
//        $data = $movies->toArray();
//        $data['data'] = $items;
        return new MovieCollection($movies);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Genre $genre
     * @return Response
     */
    public function edit(Genre $genre)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Genre $genre
     * @return Response
     */
    public function update(Request $request, Genre $genre)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Genre $genre
     * @return Response
     */
    public function destroy(Genre $genre)
    {
        //
    }
}

resources/views/genre/index.blade.php
<x-layouts.user>

    <div class="uk-container uk-margin-large-top uk-margin-bottom">
        <div class="uk-hidden@m uk-margin-xlarge-top"></div>

        <ul class="uk-breadcrumb uk-margin-top">
            <li><a href="{{route('homepage')}}">Home</a></li>
            <li><span>Genres</span></li>
        </ul>

        <div class="uk-child-width-1-2@m uk-child-width-1-3@l uk-child-width-1-4@xl" uk-grid
            uk-scrollspy="cls:uk-animation-slide-top-small;delay: 80;target:a">
            @foreach(\App\Models\Genre::all() as $genre)


            <a href="{{route('genres.show', ['genre'=>strtolower($genre->name)])}}">
                <div>
                    <div class="uk-inline uk-transition-toggle uk-overflow-hidden">
                        <img src="https://loremflickr.com/320/240/{{$genre->name}}" width="1800" height="1200" alt="">
                        <div class="uk-overlay uk-overlay-primary uk-position-top uk-padding-remove-vertical">
                            <h3 class="uk-margin-medium-top">{{$genre->name}}</h3>
                            @php($count = ($genre??null)->movies->count())
                            <div class="uk-card-badge uk-label uk-transition-slides-top">{{$count}}
                                {{\Illuminate\Support\Str::plural("movie", $count)}}</div>
                        </div>
                    </div>
                </div>
            </a>


            @endforeach
        </div>
    </div>

</x-layouts.user>

resources/views/genre/single.blade.php
<x-layouts.user>

    @php
    if(!isset($genre))
    throw new Error();
    $movies = App\Models\Movie::query()->whereBelongsTo($genre)->paginate(16);
    @endphp


    <div class="uk-container uk-margin-large-top uk-light">
        <div class="uk-hidden@m uk-margin-xlarge-top"></div>
        <ul class="uk-breadcrumb uk-margin-top">
            <li><a href="{{route('homepage')}}">Home</a></li>
            <li><a href="{{route('genres.index')}}">Genres</a></li>
            <li><span>{{$genre->name}}</span></li>
        </ul>

        <h1 class="uk-heading-medium uk-margin-top">{{$genre->name}}</h1>
        <div id="movies-list"
            {{-- class="uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-child-width-1-5@l uk-child-width-1-6@xl" --}}
            uk-grid {{-- uk-scrollspy="cls:uk-animation-slide-top-small;delay: 80;target:>div" --}}>
        </div>
        <span id="bottom-detector" uk-scrollspy="repeat:true"></span>

        @push('scripts')

        <script src="/js/homepage/genre.js"></script>
        <script>
            document.addEventListener('DOMContentLoaded', ()=>{
                initListener(1, "{{route('genre.movies.page', ['id'=>$genre->hashid()])}}", "{{route('movie.thumbnailComponent')}}");
            });
        </script>
        @endpush
    </div>

    {{--
    <x-movie.thumbnail id="thumbnail" class="uk-hidden" :movie="null" /> --}}

</x-layouts.user>